#%RAML 1.0 DataType
description: 
type: object
properties: 
  appName: 
    description: name of an API
    displayName: apiName
    type: string
    example: "accounts-papi"
    pattern: "[a-zA-Z0-9- ]+"
  serverName: 
    description: name of an API
    displayName: serverName
    type: string
    example: "ngusapp51"
    pattern: "[a-zA-Z0-9- ]+"
  status: 
    description: name of an API
    displayName: status
    type: string
    example: "Active"
    pattern: "[a-zA-Z0-9- ]+"
  date: 
    description: name of an API
    displayName: status
    type: datetime
    example:  2019-01-21T18:25:43-05:00