#%RAML 1.0 Library
usage: Library containing all New Opportunity Creation project data types.

types: 
  HealthStatus: !include ../data-types/response/health-status.raml
  Payload:
    type: object
    properties:
      status: number
      payload: object
    example: !include ../examples/201-generic-payload.raml
