#%RAML 1.0 Library
resourceTypes:
  CreateOnlyResourceType: !include /resource-types/create-only.raml
  ReadOnlyResourceType: !include /resource-types/read-only.raml
  CreateUpdateResourceType: !include  /resource-types/create-update.raml