#%RAML 1.0 NamedExample
  {
    "status": 200,
    "payload": {
      "appName": "ntn-salesforce-sync-eapi",
      "serverName": "node",
      "status": "Active",
      "date": 2019-01-21T18:25:43-05:00
    },
    "errors": []
  }