#%RAML 1.0 NamedExample
  {
    "status": 400,
    "payload": {
      "message": "Bad Request"
    },
    "errors": [
      {
        "errorTitle": "Bad Request",
        "errorMessage": "Bad Request please retry",
        "apiName": "My API",
        "version": "v1",
        "developerMessage": "Bad Request please retry with proper combination of URL, Headers, Query Parameters",
        "errorCode": "10000",
        "moreInfo": "http://loging-server/logs/12984hs8",
        "correlationId": "XXX-XXX",
        "validationErrors": [] 
      }
    ]
  }