#%RAML 1.0 NamedExample
  {
    "status": 401,
    "payload": {
      "message:": "Unauthorized"
    },
    "errors": [
      {
        "errorTitle": "Unauthorized",
        "errorMessage": "Unauthorized Credentials for Access",
        "apiName": "My API",
        "developerMessage": "Unauthorized, Please retry with the correct credentials",
        "errorCode": "10000",
        "moreInfo": "http://loging-server/logs/12984hs8",
        "correlationId": "XXX-XXX",
        "validationErrors": [] 
      }
    ]
  }