#%RAML 1.0 NamedExample
  {
    "status": 403,
    "payload": {
      "message": "Forbidden"
    },
    "errors": [
      {
        "errorTitle": "Forbidden",
        "errorMessage": "Forbidden, Access to this resource is forbidden with the given credentials",
        "apiName": "My API",
        "version": "v1",
        "developerMessage": "Forbidden, Access to this resource is forbidden with the given credentials",
        "errorCode": "10000",
        "moreInfo": "http://loging-server/logs/12984hs8",
        "correlationId": "XXX-XXX",
        "validationErrors": [] 
      }
    ]
  }