#%RAML 1.0 NamedExample
  {
    "status": 404,
    "payload": {
      "message": "Not Found"
    },
    "errors": [
      {
        "errorTitle": "Not Found",
        "errorMessage": "The requested resource is not found",
        "apiName": "My API",
        "version": "v1",
        "developerMessage": "The requested resource could not be found but may be available in the future. Subsequent requests by the client are permissible.",
        "errorCode": "10000",
        "moreInfo": "http://loging-server/logs/12984hs8",
        "correlationId": "XXX-XXX",
        "validationErrors": [] 
      }
    ]
  }