#%RAML 1.0 NamedExample
  {
    "status": 500,
    "payload": {
      "message": "Internal Server Error"
    },
    "errors": [
      {
        "errorTitle": "Internal Server Error",
        "errorMessage": "Internal Server Error",
        "apiName": "My API",
        "developerMessage": "Internal Server Error",
        "errorCode": "10000",
        "moreInfo": "http://loging-server/logs/12984hs8",
        "correlationId": "XXX-XXX",
        "validationErrors": [] 
      }
    ]
  }