#%RAML 1.0 NamedExample
  {
    "status": 502,
    "payload": {
      "message": "Bad Gateway"
    },
    "errors": [
      {
        "errorTitle": "Bad Gateway",
        "errorMessage": "The server was acting as a gateway or proxy and received an invalid response from the upstream server",
        "apiName": "My API",
        "developerMessage": "The server was acting as a gateway or proxy and received an invalid response from the upstream server",
        "errorCode": "10000",
        "moreInfo": "http://loging-server/logs/12984hs8",
        "correlationId": "XXX-XXX",
        "validationErrors": [] 
      }
    ]
  }